### ISSUE TITLE
file_get_contents(C:\xampp\htdocs\AngLara\public\build/rev-manifest.json): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by 71anshuman** [silverbux/laravel-angular-admin#43]
file_get_contents(C:\xampp\htdocs\AngLara\public\build/rev-manifest.json): failed to open stream: No such file or directory (View: C:\xampp\htdocs\AngLara\resources\views\index.blade.php)

**Comment by silverbux** [comment]
have you tried running ```gulp && gulp watch``` ?
