### ISSUE TITLE
composer install errors

### ISSUE THREAD

**Issue by yugasun** [silverbux/laravel-angular-admin#46]
## When I run command 'composer install', the bellow erros come, can you help me?

The "fxp/composer-asset-plugin" plugin was skipped because it requires a Plugin API version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for namshi/jose 5.0.2 -> satisfiable by namshi/jose[5.0.2].
    - namshi/jose 5.0.2 requires lib-openssl * -> the requested linked library openssl has the wrong version installed or is missing from your system, make sure to have the extension providing it.
  Problem 2
    - namshi/jose 5.0.2 requires lib-openssl * -> the requested linked library openssl has the wrong version installed or is missing from your system, make sure to have the extension providing it.
    - tymon/jwt-auth 0.5.9 requires namshi/jose 5.0.* -> satisfiable by namshi/jose[5.0.2].
    - Installation request for tymon/jwt-auth 0.5.9 -> satisfiable by tymon/jwt-auth[0.5.9].

**Comment by silverbux** [comment]
seems like a an lib-openssl issue, try checking this solution.
http://stackoverflow.com/questions/37534271/lib-openssl-dependency-issue-laravel-and-composer-on-osx

**Comment by yugasun** [comment]
thx! I have solved the issue~
