### ISSUE TITLE
Does this compatible with laravel5-angular-material-starter?

### ISSUE THREAD

**Issue by followtheart** [silverbux/laravel-angular-admin#47]
Does this project compatible with laravel5-angular-material-starter?

Any advice for integration with [ laravel5-angular-material-starter](https://github.com/jadjoubran/laravel5-angular-material-starter.git)

**Comment by silverbux** [comment]
Hi! first what are you trying to achieve?

**Comment by followtheart** [comment]
I have an project based on [ laravel5-angular-material-starter](https://github.com/jadjoubran/laravel5-angular-material-starter.git),and want to add a admin interface like this project

**Comment by silverbux** [comment]
i guess you could start by adding your existing angular components (dont forget to import in index.components.js).
add your existing backend (laravel codes).
add/setup your angular and laravel routes.
then finally migrate your views from material design to bootstrap.
