### ISSUE TITLE
Role Based Access Control

### ISSUE THREAD

**Issue by thecortex** [silverbux/laravel-angular-admin#48]
Hello,

Are the permissions assigned to the user? In a Role Based Access Control should not permissions be assigned to roles and users assigned to roles. Then, users are granted these permission through the roles. Or what is the point to assign both roles and permissions directly to the user?

A link explaining why it is so:
https://lostechies.com/derickbailey/2011/05/24/dont-do-role-based-authorization-checks-do-activity-based-checks/

Thank you,

**Comment by silverbux** [comment]
At the current approach yes permissions are assigned to roles and users are assigned to roles. 
in terms of why assign both roles and permission to users, i guess its case to case basis
for example a you have an analytics.admin and content.writers.admin, there are cases like content.writers want to see from analytics which contents are popular but you dont want to give full permission to the entire analytics module.

but this havent been implemented yet, with the way [bican/roles] (https://github.com/romanbican/roles#attaching-and-detaching-permissions) been coded i think it's pretty flexible, it's just that the goal is to make it more flexible as possible.

**Comment by thecortex** [comment]
Dear Alex,

Thank you for the clarification. It's indeed more flexible, and could you please provide a link to the permission-role assignment action if it exists in current release?

Regards,

**Comment by silverbux** [comment]
np 😉
