### ISSUE TITLE
How to enable auto/live reload

### ISSUE THREAD

**Issue by makusan** [silverbux/laravel-angular-admin#49]
Hello,

How do i enable the auto/live reload function when editing files? 
Mine is not working after default installation

```
.browserSync({
      proxy: 'localhost:8000',
      files: [ 'public/**/*.css', 'angular/pages/**/*.page.html' ]
})
```

**Comment by silverbux** [comment]
``` gulp watch ``` should do it. also there's a current bug that whenever you create a new file for example a new component, you have to restart gulp watch

**Comment by makusan** [comment]
I did that, but even editing the css files, it is not autoreload as it should. 
Could it be because i did not run

`php artisan serve --host=0`

im getting error if i set the host=0
```
$ php artisan serve --host=0
Laravel development server started on http://0:8000/
[Tue Jun 28 16:34:59 2016] PHP Warning:  Unknown: php_network_getaddresses: getaddrinfo failed: No such host is known.  in Unknown on line 0
[Tue Jun 28 16:34:59 2016] Failed to listen on 0:8000 (reason: php_network_getaddresses: getaddrinfo failed: No such host is known. )
```

Do you know how to bind that on windows ?

Thanks for replying

**Comment by makusan** [comment]
Nevermind, i switched to vagrant instead

**Comment by makusan** [comment]
Btw, we can use php artisan serve --host=0.0.0.0
