### ISSUE TITLE
can't use new module

### ISSUE THREAD

**Issue by filmsklz** [silverbux/laravel-angular-admin#54]
I can not use 'chart.js' .
I am install chart.js with bower and add it like this " **angular.module('app.components', ['chart.js'])** "
when refresh my site, show errors

> angular.js:68Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
> Error: [$injector:modulerr] Failed to instantiate module app.components due to:
> Error: [$injector:modulerr] Failed to instantiate module chart.js due to:
> Error: [$injector:nomod] Module 'chart.js' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

how can i fix this problem ? 
thank you

**Comment by ixperiencenl** [comment]
Hi filmskiz, in the default package, chart is already included. It's also already in the index.modules.js file added like angular.module('app.components'),['chart.js', etc etc])

To add it into your component, add **chart** to your constructor.

**Comment by filmsklz** [comment]
When i want to import other module with bower ,What should I do ? 
Now i'm add package name into angular.module('app.components') but can not working.

**Comment by silverbux** [comment]
hi @filmsklz you're probably missing angular-chart.js in your bower.json see [bower.json#L24](https://github.com/silverbux/laravel-angular-admin/blob/master/bower.json#L24). update your file and do a ```bower install```

**Comment by filmsklz** [comment]
Thank you ,The problem is solved.

**Comment by donadoniman** [comment]
how can i enable select2 or datetimepicker on my project

**Comment by donadoniman** [comment]
may i know the steps to add new modules from bower_components
