### ISSUE TITLE
[question] acl: protect a route

### ISSUE THREAD

**Issue by andresrivas1506** [silverbux/laravel-angular-admin#56]
can someone help me to use this https://github.com/mikemclin/angular-acl#protect-a-route to protect ui-routes?

**Comment by silverbux** [comment]
Hi @andresrivas1506 , its already implemented by default, on protected routes you simply add 
``` data { auth: true } ``` **example:** [routes.config.js#L36] ( https://github.com/silverbux/laravel-angular-admin/blob/master/angular/config/routes.config.js#L36 )

and to show / hide elements use ```vm.can()``` [nav-sidebar.component.html#L28](https://github.com/silverbux/laravel-angular-admin/blob/master/angular/app/components/nav-sidebar/nav-sidebar.component.html#L28) which is referenced on its controller [nav-sidebar.component.js#L6](https://github.com/silverbux/laravel-angular-admin/blob/master/angular/app/components/nav-sidebar/nav-sidebar.component.js#L6)

**Comment by andresrivas1506** [comment]
Hello @silverbux thanks for your time. Yes, its already implemented, but only using `data { auth: true }` and showing/hiding things in template. If you go, for example, to url http://myapp/#/user-lists from url bar, you can see the html.

I want to protect the route using permissions:

```javascript
.when('/content', {
      resolve : {
        'acl' : ['$q', 'AclService', function($q, AclService){
          if(AclService.can('view_content')){
            // Has proper permissions
            return true;
          } else {
            // Does not have permission
            return $q.reject('Unauthorized');
          }
        }]
      }
    });
```

Sorry for my bad english

**Comment by andresrivas1506** [comment]
I can solve with this:

* In [routes.run.js#L48](https://github.com/silverbux/laravel-angular-admin/blob/master/angular/run/routes.run.js#L48)

```javascript
$rootScope.$on('$stateChangeError', function (event, toState, toParams, fromState, fromParams, rejection) {
    if (rejection === 'Unauthorized') {
      $state.go('app.landing');
    }
  });
```
* my protected route

```javascript
.state('app.someorute', {
      url: '/someroute',
      resolve : {
        'acl' : ['$q', 'AclService', function($q, AclService){
          if(AclService.can('some_permission')){
            // Has proper permissions
            return true;
          } else {
            // Does not have permission
            return $q.reject('Unauthorized');
          }
        }]
      },
      data: {
        auth: true
      },
      views: {
        'main@app': {
          templateUrl: getView('some')
        }
      }
    })
```

Thank you @silverbux

**Comment by silverbux** [comment]
Coolness, or try this approach as well.
```
data: {
   auth: true,
   access: 'manage.user'
}
```

then  you could add a function on your [/angular/run/routes.run.js](https://github.com/silverbux/laravel-angular-admin/blob/master/angular/run/routes.run.js#L7) and call AclService from there.

**Comment by andresrivas1506** [comment]
very nice that approach, thanks
