### ISSUE TITLE
Error: the fixed layout requires the slimscroll plugin!

### ISSUE THREAD

**Issue by stranger26** [silverbux/laravel-angular-admin#57]
Hey there,

I was wondering how do I enable the slimscroll plugin? Thank you!

**Comment by silverbux** [comment]
try [angular-slimscroll] (https://github.com/ziscloud/angular-slimscroll) or [ng-slim-scroll](https://github.com/ytlabs/ng-slim-scroll)

**Comment by stranger26** [comment]
Thank you! Prefer angular-slimscroll anw! 👍
