### ISSUE TITLE
Bootstrap modals have lost their rounded corners

### ISSUE THREAD

**Issue by saulojg** [silverbux/laravel-angular-admin#59]
This one can be reproduced easily, the modals at the [demo](http://laravel-admin.herokuapp.com/#/ui-modal) have lost their rounded corners, as it can be seen on the Bootstrap homepage or at [angular-ui](https://angular-ui.github.io/bootstrap/)

Thanks in advance and kudos

**Comment by silverbux** [comment]
its been removed from adminlte, you could set this with ```.modal-content { border-radius: 6 }```

**Comment by pdugas** [comment]
I think this should be `.modal-content { border-radius: 6px }`.  Needs the `px` suffix to work for me.
