### ISSUE TITLE
application path issue

### ISSUE THREAD

**Issue by kingvish** [silverbux/laravel-angular-admin#65]
Hello,
I am trying to setup this application on xampp with  this way    "localhost/laraang".
after setup when i visit in browser i found issue with path generated via elixer:
<link rel="stylesheet" href="/build/css/final-13f33a294f.css">
which result in localhost/build/css/final-13f33a294f.css  not found. t

Is there a way to setup this app on subdirectory? any checklist or suggestion?

Many Thanks!

**Comment by silverbux** [comment]
have you tried executing a ```gulp``` command?

**Comment by kingvish** [comment]
yes, I have executed gulp command. The issue is similar to https://github.com/laravel/elixir/issues/501

I have   trimmed two line from index.blade.php  and remove  '/' from left and i can see login page. 
 ltrim (elixir('css/final.css'),'/')
 ltrim( elixir('js/final.js'),'/')

But, on next after clicking on login submit goes to http://localhost/api/auth/login instead of http://localhost/tutorapp/api/auth/login 

Am I missing some common setting or something else?

**Comment by silverbux** [comment]
currently all settings and endpoint are pointed to root of domain "/" , you have to edit settings for this, or just do a ```php artisan serve --host=0``` or ```php artisan serve```
