### ISSUE TITLE
A verification link in not arrive email

### ISSUE THREAD

**Issue by sarmugim** [silverbux/laravel-angular-admin#68]
A verification link  is not arrive my mail .so i can't login page . How can i do that ..Thanks .

  'from' => ['address' => env('MAIL_FROM', xxxx@gmail.com), 'name' => env('MAIL_FROM_NAME', sarmu)],

**Comment by silverbux** [comment]
make sure you set your mail server settings on your ```.env``` file, 
```
MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM=no-null
MAIL_FROM_NAME=''
```

**Comment by silverbux** [comment]
this might help

- [ultimate-guide-on-sending-email-in-laravel](https://scotch.io/tutorials/ultimate-guide-on-sending-email-in-laravel)

- [mailsend-with-mail-driver-in-localhost-is-not-delivered](http://stackoverflow.com/questions/27699407/mailsend-with-mail-driver-in-localhost-is-not-delivered)

**Comment by sarmugim** [comment]
Thanks a lots silverbux .. It is working for me ..
