### ISSUE TITLE
Project is not running

### ISSUE THREAD

**Issue by aksuhana** [silverbux/laravel-angular-admin#69]
I am getting the following error 

file_get_contents(/var/www/html/LA/public/build/rev-manifest.json): failed to open stream: No such file or directory (View: /var/www/html/LA/resources/views/index.blade.php)

where /var/www/html/LA is my Project Directory. I followed the processes of installation . when I trigger php artisan serve and try to run it on localhost:8000 , then I got the error.

**Comment by silverbux** [comment]
you have a wrong build path, try checking your ```elixir.json``` and enter correct path. then rebuild again by ```gulp --production```

**Comment by aksuhana** [comment]
elixer path is /var/www/html/LA/elixir.json
**Here is the same copy paste code for index.balde.php file**
<!doctype html>
<html ng-app="app">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{!! elixir('css/final.css') !!}">
    <link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic'>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <title>Laravel Angular Admin-LTE</title>
    
    
    
</head>
<body route-bodyclass>
    <div class="wrapper">
        <div ui-view="layout"></div>
        <div class="control-sidebar-bg"></div>
    </div>
    <script src="{!! elixir('js/final.js') !!}" async defer></script>
</body>
</html>

**Comment by silverbux** [comment]
yep open ```/var/www/html/LA/elixir.json``` and put correct path, then rebuild using ```gulp --production```

**Comment by aksuhana** [comment]
Kindly share me where and how to change the path....
This is my elixir.json  file with path `/var/www/html/LA/elixir.json`


`{
    "js": {
        "outputFolder": "public/js"
    },
    "css": {
        "outputFolder": "public/css",
        "sass": {
            "folder": "../../angular/"
        },
        "lteSkin": "skin-blue.css"
    },
    "fonts": {
        "outputFolder": "public/fonts"
    },
    "buildPath": "public/build"
}
`
