### ISSUE TITLE
Deploying to server

### ISSUE THREAD

**Issue by stranger26** [silverbux/laravel-angular-admin#78]
Hi there, I have been developing a dashboard with this template, and I want to deploy to my own server instead of Heroku. How do I go about it?

**Comment by silverbux** [comment]
best option is to use **continuous deployment** , but if not available for you, you could simply create a private GIT repository (bitbucket is free), clone it to your server, then basically the process is the same do a `composer install` and `gulp --production`, then simply point your nginx or apache to your public folder and set necessary config.

**Comment by stranger26** [comment]
Thank you for your response, it was very helpful. However I am hosting on an IIS 7 server. I am able to display the laravel page if I run the public folder without project root only. But it shows a blank screen (the title tag is displaying the correct information) with errors fetching resources from /build when pointing to public folder with project root.
Update, it is the static routing problem. It is referring to /build in document root which it is not. Where can I change the static reference?

**Comment by ghost** [comment]
Hi, I am going to this templete to wamp server now.
But when I copied this one to laravel of wamp, I cannot run the api of this one correctly even i can see home page of this one.
So now, I think that is because i should change the configuration of this one for api or another reason.
Could anyone help me now?

**Comment by ghost** [comment]
In addition, I have replaced the default laravel folder of wamp sever to this templete, because i think this one is laravel project
Am I right?
