### ISSUE TITLE
[Feature request]: Add pagination (with solution)

### ISSUE THREAD

**Issue by ixperiencenl** [silverbux/laravel-angular-admin#80]
When retrieving loads of rows the application hangs in Chrome. This is of course because the 'all' statement is returning all data from the DB. Would be nice if pagination would be possible out of the box.

**Comment by ixperiencenl** [comment]
this is a datatables issue, sorry for bothering

**Comment by tyro044** [comment]
thank you. Appreciated

**Comment by ixperiencenl** [comment]
A follow up on my request: to use pagination (and server side speed) for datatables I suggest installing the https://datatables.yajrabox.com/starter package. Then use the ajax calls from datatables itself to work with it. Don't forget to submit the authorization header first.
