### ISSUE TITLE
Launch without "php artisan serve --host=0"

### ISSUE THREAD

**Issue by zinaLacina** [silverbux/laravel-angular-admin#87]
Can I launch my url like http;//localhost/<my project> directly? Because <php artisan serve --host=0>use enormous my CPU

**Comment by silverbux** [comment]
havent tried it yet but surely it's possible just a matter of finding and changing right config

**Comment by zinaLacina** [comment]
Thank you for your attention. Thank for your great job. I would try to look for some solution and I come back if I'll meet some difficulty.
