### ISSUE TITLE
On fresh install on fresh VM

### ISSUE THREAD

**Issue by ProxyAi** [silverbux/laravel-angular-admin#89]
Here what it looks like in broswer
![image](https://cloud.githubusercontent.com/assets/11992984/21680759/a33386b2-d343-11e6-8e48-f3e7fc2d4fd8.png)

before you think file permissions 
https://gist.github.com/xorenio/97d1f6f6511c2a50100c

versions
---------
$ php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies

$ node -v
v7.4.0

$ npm -v
4.0.5

----
im using this to temp host as i build/play
$ php -S 0.0.0.0:8000 -t public/

**Comment by silverbux** [comment]
after ```composer install && npm install``` do a ```gulp && gulp watch```

**Comment by ProxyAi** [comment]
Cheers i can't believe i was so silly to miss
