### ISSUE TITLE
installation error in localdevelopment

### ISSUE THREAD

**Issue by didinkaj** [silverbux/laravel-angular-admin#97]
PHP Warning:  require(C:\xampp\htdocs\tally\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\tally\bootstrap\autoload.php on line 17

**Comment by silverbux** [comment]
you executed ```composer install``` ?

**Comment by didinkaj** [comment]
yeap now getting
RuntimeException in EncryptionServiceProvider.php line 45: No supported encrypter found. The cipher and / or key length are invalid.

**Comment by silverbux** [comment]
Open ```.env``` file, if it does not exists copy ```.env.example``` file . and enter credentials.
then try to do ```php artisan key:generate```
